version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '05:00'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '05:00'
    groups:
      dependencies:
        applies-to: 'version-updates'
        update-types:
          - 'minor'
          - 'patch'
