overrides:
  next: 16.2.9
  tailwindcss: ^4.3.1
  minimatch@3>brace-expansion: 1.1.14
  gray-matter>js-yaml: 3.14.2
  mdast-util-to-hast: 13.2.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
